include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    use_build_context_synchronously: false
    always_declare_return_types: true
    prefer_is_empty: true
    prefer_is_not_empty: true