name: atalay
description: Atalay Mobile Application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  google_fonts: ^2.3.1
  flutter_svg: ^1.0.3
  easy_localization: ^3.0.0
  flutter_zoom_drawer: ^2.3.1
  step_progress_indicator: ^1.0.2
  calendar_view: ^0.0.4
  extended_image: ^6.0.1
  story:
    path: packages/story/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_native_splash: ^2.0.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

flutter_native_splash:
  color: "#004566"
  image: assets/images/logo.png