name: atalay
description: Atalay Mobile Application
project_author: Yunus Karaaslan
project_author_email: karaaslan.21@hotmail.com
project_author_phone: +905319823347

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  provider: ^6.0.2
  flutter_native_splash: ^2.1.6
  google_fonts: ^2.3.2
  flutter_svg: ^1.0.3
  easy_localization: ^3.0.0
  flutter_zoom_drawer: ^3.0.1
  step_progress_indicator: ^1.0.2
  calendar_view: ^0.0.4
  connectivity_plus: ^2.3.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.2
  animated_shimmer: ^1.0.0
  modal_bottom_sheet: ^2.0.1
  email_validator: ^2.0.1
  image_picker: ^0.8.5+2
  flutter_settings_ui: ^2.0.1
  image_viewer:
    path: 'packages/image_viewer/'
  base_dialog:
    path: 'packages/base_dialog/'
  firebase_core: ^1.16.0
  firebase_app_installations: ^0.1.0+12
  flutterfire_ui: ^0.4.0+5
  firebase_auth: ^3.3.17
  firebase_performance: ^0.8.0+11
  firebase_crashlytics: ^2.7.2
  firebase_analytics: ^9.1.7
  firebase_in_app_messaging: ^0.6.0+13
  firebase_messaging: ^11.3.0
  cloud_firestore: ^3.1.14
  firebase_storage: ^10.2.15
  firebase_app_check: ^0.0.6+11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - android/app/build.gradle

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

flutter_native_splash:
  color: "#004566"
  image: assets/images/logo.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"