name: atalay
description: Atalay Mobile Application
project_author: Yunus Karaaslan
project_author_email: karaaslan.21@hotmail.com
project_author_phone: '+905319823347'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  provider: ^6.0.2
  google_fonts: ^2.3.1
  flutter_svg: ^1.0.3
  easy_localization: ^3.0.0
  flutter_zoom_drawer: ^2.3.1+1
  step_progress_indicator: ^1.0.2
  calendar_view: ^0.0.4
  connectivity_plus: ^2.2.1
  image_viewer:
    path: 'packages/image_viewer/'
  firebase_core: ^1.13.1
  firebase_app_installations: ^0.1.0+8
  flutterfire_ui: ^0.3.6
  firebase_auth: ^3.3.10
  firebase_performance: ^0.8.0+7
  firebase_crashlytics: ^2.5.3
  firebase_analytics: ^9.1.2
  firebase_in_app_messaging: ^0.6.0+9
  firebase_messaging: ^11.2.10
  email_validator: ^2.0.1
  image_picker: ^0.8.4+11
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_native_splash: ^2.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - android/app/build.gradle

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

flutter_native_splash:
  color: "#004566"
  image: assets/images/logo.png